language: node_js
node_js:
  - '8'
addons:
  sauce_connect:
    username: leonardo.oliveira
    access_key: 5c0d3123-8a68-4f31-9dbc-7b8756ce18c8
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm run test
